import sys
import os
import json
import traceback
import random
import numpy as np

# Add project root to sys.path
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

import gymnasium as gym
from highwayenv.utils import patch_intersection_env, register_intersection_env
from src.experiment import scenarios_config as sc
from src.experiment.scenarios import base_complete_scenarios_3_cars

# PDF Generation Imports
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, KeepTogether
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.pdfgen import canvas

# Define modern palette
PRIMARY_COLOR = colors.HexColor("#1e3a8a")     # Deep Blue
SECONDARY_COLOR = colors.HexColor("#0f766e")   # Teal
DARK_NEUTRAL = colors.HexColor("#1e293b")      # Charcoal
LIGHT_NEUTRAL = colors.HexColor("#f8fafc")     # Light gray/blue
SUCCESS_COLOR = colors.HexColor("#16a34a")     # Soft Green
WARNING_COLOR = colors.HexColor("#ea580c")     # Soft Orange
DANGER_COLOR = colors.HexColor("#dc2626")      # Soft Red
LINE_COLOR = colors.HexColor("#cbd5e1")        # Border Gray

class NumberedCanvas(canvas.Canvas):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count):
        self.saveState()
        
        # Header (pages > 1)
        if self._pageNumber > 1:
            self.setFont("Helvetica", 8)
            self.setFillColor(DARK_NEUTRAL)
            self.drawString(54, 750, "Intersection Scenarios Solvability Test Report")
            self.setStrokeColor(LINE_COLOR)
            self.setLineWidth(0.5)
            self.line(54, 742, 558, 742)
        
        # Footer
        self.setFont("Helvetica", 8)
        self.setFillColor(DARK_NEUTRAL)
        self.drawString(54, 36, "Antigravity Autonomous Driving RL Research Suite")
        page_str = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(558, 36, page_str)
        self.setStrokeColor(LINE_COLOR)
        self.setLineWidth(0.5)
        self.line(54, 48, 558, 48)
        
        self.restoreState()


def run_scenario_tests():
    print("Initializing Scenario Test Runner (Permutations Mode)...")
    patch_intersection_env()
    register_intersection_env()

    # Create config
    env_config = sc.full_env_config_exp5
    # Ensure RENDER_MODE is None to run faster and headless
    env_config["render_mode"] = None

    print("Creating RELintersection-v0 environment...")
    env = gym.make('RELintersection-v0', config=env_config)

    # Reconstruct the 72 scenarios in the exact order generated by the environment
    from highwayenv.intersection_class import rotate_scenario_clockwise

    def rotate_complete_scenario(scenario, rotation):
        def rotate_lane_id(lane_id, rotation):
            if len(lane_id) < 2 or not lane_id[-1].isdigit():
                return lane_id
            prefix = lane_id[:-1]
            direction = int(lane_id[-1])
            new_direction = (direction + rotation) % 4
            return prefix + str(new_direction)

        def rotate_scenario_clockwise_local(scenario, rotation):
            rotated_scenario = []
            for lane_key, destination, offset in scenario:
                if isinstance(lane_key, tuple):
                    rotated_lane = tuple(
                        rotate_lane_id(part, rotation) if isinstance(part, str) else part
                        for part in lane_key
                    )
                else:
                    rotated_lane = rotate_lane_id(lane_key, rotation)
                rotated_dest = rotate_lane_id(destination, rotation)
                rotated_scenario.append((rotated_lane, rotated_dest, offset))
            return rotated_scenario

        rotated_agents = [rotate_scenario_clockwise_local([agent], rotation)[0] for agent in scenario["agents"]]
        rotated_static = [rotate_scenario_clockwise_local([static], rotation)[0] for static in scenario["static"]]
        return {
            "agents": rotated_agents,
            "static": rotated_static
        }

    all_scenarios = []
    for base_scenario in base_complete_scenarios_3_cars:
        all_scenarios.append(base_scenario)
        for rotation in [1, 2, 3]:
            rotated_scenario = rotate_complete_scenario(base_scenario, rotation)
            all_scenarios.append(rotated_scenario)

    print(f"Total scenario blueprints loaded: {len(all_scenarios)}")

    # Monkeypatch random.choice
    original_choice = random.choice
    forced_scenario = None

    def patched_choice(seq):
        # Identify the correct scenario list reset invocation
        if isinstance(seq, list) and len(seq) == 72 and isinstance(seq[0], dict) and "agents" in seq[0]:
            return forced_scenario
        return original_choice(seq)

    random.choice = patched_choice

    results = []

    # Run each scenario
    for idx in range(72):
        forced_scenario = all_scenarios[idx]
        base_idx = idx // 4
        rotation_idx = idx % 4
        rotation_names = ["Original", "90° CW", "180° CW", "270° CW"]
        
        print(f"Testing Scenario {idx:02d}/71: Base {base_idx:02d} ({rotation_names[rotation_idx]})...")
        
        scenario_status = {
            "scenario_index": idx,
            "base_scenario_index": base_idx,
            "rotation": rotation_names[rotation_idx],
            "num_agents": len(forced_scenario["agents"]),
            "num_static": len(forced_scenario["static"]),
            "status": "COLLISION", # Default to collision unless validated
            "exception": None,
            "agent_collision": True,
            "steps_run": 0,
            "arrived_count": 0,
            "permutations_tested": 0,
            "successful_permutation": -1
        }

        try:
            validated = False
            for p in range(100):
                scenario_status["permutations_tested"] += 1
                
                # Seed python and numpy random for reproducibility of this permutation trajectory
                random.seed(p)
                np.random.seed(p)
                
                # Reset environment
                obs, info = env.reset()
                
                # Clear arrival flags for new episode
                if hasattr(env.unwrapped, 'arrived_vehicles'):
                    env.unwrapped.arrived_vehicles.clear()
                
                done = False
                truncated = False
                steps = 0
                max_steps = 60
                collision_occurred = False
                
                while not done and not truncated and steps < max_steps:
                    # Choose action tuple based on permutation index
                    # Permutation 0: All 0s (SLOWER)
                    # Permutation 1: All 1s (FASTER)
                    # Permutation 2+: Randomly sample actions for each vehicle
                    if p == 0:
                        action = tuple(0 for _ in range(len(env.unwrapped.controlled_vehicles)))
                    elif p == 1:
                        action = tuple(1 for _ in range(len(env.unwrapped.controlled_vehicles)))
                    else:
                        action = tuple(random.choice([0, 1]) for _ in range(len(env.unwrapped.controlled_vehicles)))
                    
                    obs, reward, done, truncated, info = env.step(action)
                    steps += 1
                    
                    # Check for agent collision
                    if any(getattr(v, 'crashed', False) for v in env.unwrapped.controlled_vehicles):
                        collision_occurred = True
                        break
                
                if not collision_occurred:
                    # Found a collision-free action sequence!
                    validated = True
                    scenario_status["status"] = "SUCCESS"
                    scenario_status["agent_collision"] = False
                    scenario_status["steps_run"] = steps
                    scenario_status["successful_permutation"] = p
                    scenario_status["arrived_count"] = sum(1 for v in env.unwrapped.controlled_vehicles if getattr(v, 'is_arrived', False))
                    print(f"  -> VALIDATED on permutation {p:02d} (Steps: {steps}, Arrived: {scenario_status['arrived_count']}/{scenario_status['num_agents']})")
                    break
            
            if not validated:
                print(f"  -> FAILED all 100 permutations (All collided).")
                scenario_status["steps_run"] = steps
                scenario_status["arrived_count"] = sum(1 for v in env.unwrapped.controlled_vehicles if getattr(v, 'is_arrived', False))

        except Exception as e:
            tb = traceback.format_exc()
            print(f"  CRASHED (Python Exception) in scenario {idx}: {e}")
            scenario_status["status"] = "EXCEPTION"
            scenario_status["exception"] = str(e)
            scenario_status["tb"] = tb
            scenario_status["agent_collision"] = False

        results.append(scenario_status)

    # Save solvable scenarios list (No Exception Code Crashes)
    solvable_indices = [r["scenario_index"] for r in results if r["status"] != "EXCEPTION"]
    validated_indices = [r["scenario_index"] for r in results if r["status"] == "SUCCESS"]

    output_data = {
        "solvable_scenarios": solvable_indices, # Solvable in terms of code not crashing
        "validated_collision_free_scenarios": validated_indices, # Scenarios that have at least 1 collision-free path
        "total_scenarios_tested": len(results),
        "results": results
    }

    # Write output file
    output_path = "scenario_testing/solvable_scenarios.json"
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        json.dump(output_data, f, indent=4)
    print(f"Solvable scenarios saved to {output_path}")

    # Generate PDF Report
    generate_pdf_report(results, solvable_indices, validated_indices)
    print("Report generated successfully: scenario_testing/scenario_test_report.pdf")


def generate_pdf_report(results, solvable_indices, validated_indices):
    pdf_path = "scenario_testing/scenario_test_report.pdf"
    
    # Page settings: letter size is 8.5 x 11 inches (612 x 792 pt). Margin 54pt (0.75in)
    doc = SimpleDocTemplate(
        pdf_path,
        pagesize=letter,
        leftMargin=54,
        rightMargin=54,
        topMargin=54,
        bottomMargin=54
    )

    styles = getSampleStyleSheet()
    
    # Custom premium styles
    title_style = ParagraphStyle(
        'CoverTitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=24,
        leading=30,
        textColor=PRIMARY_COLOR,
        alignment=0, # Left
        spaceAfter=10
    )
    
    subtitle_style = ParagraphStyle(
        'CoverSubtitle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=11,
        leading=15,
        textColor=SECONDARY_COLOR,
        spaceAfter=25
    )
    
    h1_style = ParagraphStyle(
        'Header1',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=15,
        leading=19,
        textColor=PRIMARY_COLOR,
        spaceBefore=12,
        spaceAfter=8,
        keepWithNext=True
    )

    body_style = ParagraphStyle(
        'Body',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9.5,
        leading=13.5,
        textColor=DARK_NEUTRAL,
        spaceAfter=6
    )

    bold_body_style = ParagraphStyle(
        'BoldBody',
        parent=body_style,
        fontName='Helvetica-Bold'
    )
    
    code_style = ParagraphStyle(
        'Code',
        parent=styles['Code'],
        fontSize=8,
        leading=10,
        textColor=DARK_NEUTRAL,
        backColor=LIGHT_NEUTRAL,
        borderColor=LINE_COLOR,
        borderWidth=0.5,
        borderPadding=6,
        spaceAfter=10
    )

    story = []

    # Title Banner Block
    story.append(Paragraph("Intersection Scenarios Solvability Test Report", title_style))
    story.append(Paragraph("Evaluating 100 permutation trajectories for each of the 72 scenarios to validate collision-free pathways.", subtitle_style))
    story.append(Spacer(1, 8))

    # Executive Summary Card
    total_count = len(results)
    success_count = sum(1 for r in results if r["status"] == "SUCCESS")
    collision_count = sum(1 for r in results if r["status"] == "COLLISION")
    exception_count = sum(1 for r in results if r["status"] == "EXCEPTION")
    total_permutations_simulated = sum(r["permutations_tested"] for r in results)

    kpi_data = [
        [
            Paragraph("<b>TOTAL SCENARIOS</b>", body_style),
            Paragraph("<b>NO CODE CRASH (Solvable)</b>", body_style),
            Paragraph("<b>VALIDATED (Collision-Free)</b>", body_style)
        ],
        [
            Paragraph(f"<font size=18 color='#1e3a8a'><b>{total_count}</b></font>", body_style),
            Paragraph(f"<font size=18 color='#16a34a'><b>{len(solvable_indices)} / {total_count}</b></font>", body_style),
            Paragraph(f"<font size=18 color='#0f766e'><b>{success_count} / {total_count}</b></font>", body_style)
        ],
        [
            Paragraph(f"{total_permutations_simulated:,} runs simulated", body_style),
            Paragraph(f"{len(solvable_indices)/total_count*100:.1f}% syntax pass rate", body_style),
            Paragraph(f"{success_count/total_count*100:.1f}% collision-free rate", body_style)
        ]
    ]

    kpi_table = Table(kpi_data, colWidths=[150, 180, 174])
    kpi_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), LIGHT_NEUTRAL),
        ('ALIGN', (0,0), (-1,-1), 'CENTER'),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ('BOTTOMPADDING', (0,0), (-1,0), 2),
        ('TOPPADDING', (0,1), (-1,1), 2),
        ('BOTTOMPADDING', (0,1), (-1,1), 6),
        ('TOPPADDING', (0,2), (-1,2), 2),
        ('BOTTOMPADDING', (0,2), (-1,2), 8),
        ('BOX', (0,0), (-1,-1), 1, PRIMARY_COLOR),
        ('INNERGRID', (0,0), (-1,-1), 0.5, LINE_COLOR),
    ]))
    
    story.append(Paragraph("Executive Summary Dashboard", h1_style))
    story.append(kpi_table)
    story.append(Spacer(1, 10))

    # Narrative explanation
    narrative = """
    This report presents findings from evaluating 72 intersection scenarios under 100 action permutations each. 
    By simulating various acceleration/deceleration profiles (random sequences of discrete actions) over a maximum of 60 steps per permutation, we tested whether there exists a collision-free action pathway for each scenario.
    If <b>at least one permutation</b> avoids a collision, the scenario is marked as <b>Validated (Collision-Free)</b>, proving it is physically solvable under a proper RL driving policy.
    """
    story.append(Paragraph(narrative, body_style))
    
    # Break down of exceptions if any
    if exception_count > 0:
        story.append(Paragraph("Code Exception Details", h1_style))
        story.append(Paragraph(f"We detected <b>{exception_count}</b> scenario configurations that caused Python code crashes. These are completely unusable in RL training and must be modified or excluded:", body_style))
        for r in results:
            if r["status"] == "EXCEPTION":
                ex_text = f"<b>Scenario {r['scenario_index']}:</b> Base {r['base_scenario_index']} ({r['rotation']}) - <i>{r['exception']}</i>"
                story.append(Paragraph(ex_text, body_style))
                story.append(Paragraph(r.get("tb", "").replace("\n", "<br/>"), code_style))
    else:
        story.append(Paragraph("Code Exception Details", h1_style))
        story.append(Paragraph("<b>Excellent!</b> Zero Python exceptions or simulation code crashes were detected across all 72 configurations. All configurations are syntactically safe for model execution.", body_style))

    story.append(Spacer(1, 10))

    # Page Break for Detailed Scenarios Table
    story.append(PageBreak())

    story.append(Paragraph("Detailed Scenarios Test Log", h1_style))
    story.append(Paragraph("Detailed validation log showing permutations tried and the successful permutation index for each scenario.", body_style))

    # Construct the big table
    table_headers = [
        Paragraph("<b>Idx</b>", bold_body_style),
        Paragraph("<b>Base Config</b>", bold_body_style),
        Paragraph("<b>Rotation</b>", bold_body_style),
        Paragraph("<b>Agents/Static</b>", bold_body_style),
        Paragraph("<b>Perms Tried</b>", bold_body_style),
        Paragraph("<b>Best Perm</b>", bold_body_style),
        Paragraph("<b>Validation Status</b>", bold_body_style)
    ]
    
    table_rows = [table_headers]
    
    for r in results:
        status_text = r["status"]
        if status_text == "SUCCESS":
            badge = Paragraph("<font color='#16a34a'><b>VALIDATED</b></font>", body_style)
            best_perm_str = f"Perm #{r['successful_permutation']}"
        elif status_text == "COLLISION":
            badge = Paragraph("<font color='#ea580c'><b>ALL COLLIDED</b></font>", body_style)
            best_perm_str = "N/A (All 100)"
        else:
            badge = Paragraph("<font color='#dc2626'><b>CODE EXCEPTION</b></font>", body_style)
            best_perm_str = "Error"

        table_rows.append([
            Paragraph(f"{r['scenario_index']:02d}", body_style),
            Paragraph(f"Base {r['base_scenario_index']:02d}", body_style),
            Paragraph(r["rotation"], body_style),
            Paragraph(f"{r['num_agents']} / {r['num_static']}", body_style),
            Paragraph(str(r["permutations_tested"]), body_style),
            Paragraph(best_perm_str, body_style),
            badge
        ])

    # Table formatting
    col_widths = [35, 65, 75, 95, 65, 65, 114]
    results_table = Table(table_rows, colWidths=col_widths, repeatRows=1)
    
    table_style = TableStyle([
        ('BACKGROUND', (0,0), (-1,0), PRIMARY_COLOR),
        ('TEXTCOLOR', (0,0), (-1,0), colors.white),
        ('ALIGN', (0,0), (-1,-1), 'LEFT'),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ('BOTTOMPADDING', (0,0), (-1,0), 6),
        ('TOPPADDING', (0,0), (-1,0), 6),
        ('INNERGRID', (0,0), (-1,-1), 0.5, LINE_COLOR),
        ('BOX', (0,0), (-1,-1), 0.5, PRIMARY_COLOR),
    ])

    # Dynamic row coloring
    for i in range(1, len(table_rows)):
        bg = LIGHT_NEUTRAL if i % 2 == 0 else colors.white
        table_style.add('BACKGROUND', (0, i), (-1, i), bg)
    
    # Overwrite header text color using paragraph styles
    header_style = ParagraphStyle(
        'HeaderStyle',
        parent=bold_body_style,
        textColor=colors.white
    )
    for j in range(len(table_headers)):
        table_rows[0][j].style = header_style

    results_table.setStyle(table_style)
    story.append(results_table)

    # Build PDF using custom numbered canvas
    doc.build(story, canvasmaker=NumberedCanvas)


if __name__ == "__main__":
    run_scenario_tests()
